name: Release and publish to Maven Central

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3

#      - name: Set up Repository
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#          server-id: ossrh
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_PASSWORD
#          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Release prepare
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          release-branch-name: "main"

          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@zdenek-zikan.cz"

          maven-args: "-P release -Dmaven.javadoc.skip=true -DskipTests -Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true"

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: "true"
          gpg-key-id: A5B891CE2AE14918
          gpg-key: ${{ secrets.GPG_KEY }}

      - name: Create release with changelog
        uses: konfer-be/action-create-release-from-tag@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}